In [2]:
import numpy as np

Creando una lista de 10 elementos 

In [3]:
lista = list(range(1, 11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Transformando la Lista en un Array

In [4]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando el tipo de estructura

In [5]:
type(arreglo)


numpy.ndarray

Corroborando el tipo de datos del arreglo

In [6]:
arreglo.dtype


dtype('int32')

Definiendo el Array de in32 a float32

In [10]:
np.array(arreglo, dtype=np.float32)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Sigue siendo un array de int32

In [11]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Transformando los datos de int32 a float32

In [12]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Tambien existe una funcion similar a Range pero ocupando arrays


In [15]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Arreglo de 2 en 2 utilizando "ARANGE"

In [17]:
arreglonuevo2 = np.arange(0, 11, 2)
arreglonuevo2

array([ 0,  2,  4,  6,  8, 10])

########ALGUNAS FUNCIONES DE NUMPY#########

Obteniendo el promedio del array(arreglo)

In [20]:
promedio = np.mean(arreglo)
promedio

5.5

Desviacion estandar

In [21]:
d_std = np.std(arreglo)
d_std

2.8722813232690143

Obteniendo la mediana del array

In [22]:
mediana = np.median(arreglonuevo)
mediana

5.5

Generación de un arreglo de 10 elementos de solo unos

In [23]:
arreglo_de_1nos = np.ones(10)
arreglo_de_1nos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Generación de un arreglo de 10 elementos de solo ceros

In [24]:
arreglo_de_0ros = np.zeros(10)
arreglo_de_0ros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Transformando el arreglo de 1nos de punto flotante a enteros

In [25]:
arreglo_int_ones = arreglo_de_1nos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

UTILIZANDO LA FUNCIÓN RANDOM


Generando arreglo aleatorio de 5 elementos

In [30]:
arreglo_random = np.random.rand(10)
arreglo_random

array([4.73076503e-01, 3.37143314e-04, 9.06170362e-01, 1.59910191e-02,
       1.40956954e-01, 9.66929219e-01, 5.01096396e-01, 3.67367854e-01,
       4.28784868e-01, 8.89370238e-01])

Generando una matriz aleatoria de 3x3

In [32]:
matriz = np.random.rand(3,3)
matriz

array([[0.48180768, 0.18928518, 0.67388117],
       [0.18892996, 0.09359344, 0.58155166],
       [0.58831693, 0.99440918, 0.32749071]])

Generando un arreglo aleatorio de 10 números enteros del 1 al 5
                    (randint)

In [86]:
arreglo_random2 = np.random.randint(1, 5, 10)
arreglo_random2

array([3, 2, 3, 2, 1, 2, 2, 4, 1, 4])

Generando una matriz aleatoria de 10 números enteros del 1 al 100

In [87]:
matriz2 = np.random.randint(1, 100, 10)
matriz2

array([32, 55, 27, 26, 80, 48, 47, 34, 82, 23])

Generando una matriz 10x10, con numeros aleatorios del 1 al 100

In [96]:
matriz3 = np.random.randint(1, 500,(10, 10))
matriz3

array([[299, 258,  13, 316,  29,  61, 483, 120, 272,  16],
       [ 58, 317, 123, 364, 216, 317, 396, 275, 396, 263],
       [ 87, 160,  13, 472, 212,  57,  54, 460,  36, 408],
       [297, 384, 323,  51, 449, 428, 307, 470, 232, 480],
       [404, 155, 152, 228, 130, 172, 338, 403, 216, 488],
       [217, 101, 112, 223, 492, 105, 336, 330,  90,   2],
       [277, 198, 223, 232, 237, 400, 319, 169, 336, 118],
       [216, 399, 414, 179, 392, 487, 235, 402, 203, 301],
       [290, 133, 283, 109, 202,   2, 374,  59, 329,  12],
       [489, 361, 263, 309, 487, 282, 323,  59,  16, 393]])