<!DOCTYPE html>
<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: Green 
        }
    </style>
</head>
<body>
    <h1>FUNCIONES PRINCIPALES NUMPY</h1>
</body>
</html>

In [1]:
import numpy as np

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Creando un arreglo secuencial de 10 elementos</h1>
</body>
</html>

In [9]:
arreglo = np.arange(1, 11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Valor Máximo del arreglo</h1>
</body>
</html>

In [10]:
print('Valor Máximo del arreglo:' , arreglo.max())

Valor Máximo del arreglo: 10



<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Posición del Valor Máximo del arreglo</h1>
</body>
</html>

In [13]:
print('El valor maximo se encuentra en la posicion :' , arreglo.argmax())

El valor maximo se encuentra en la posicion : 9


<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Valor Minimo del arreglo</h1>
</body>
</html>

In [15]:
print(f"el valor minimo del arreglo es: {min(arreglo)}")

el valor minimo del arreglo es: 1


<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Posición del Valor Minimo del arreglo</h1>
</body>
</html>

In [16]:
print(f"el valor minimo del arreglo se encuentra en la posicion : {arreglo.argmin()}")

el valor minimo del arreglo se encuentra en la posicion : 0


<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Obtener la mediana</h1>
</body>
</html>

In [17]:
mediana = np.median(arreglo)
mediana

5.5

<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Obten la media del arreglo</h1>
</body>
</html>

In [18]:
media = np.mean(arreglo)
media

5.5

<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Obten el percentil 50 del arreglo(Mediana)</h1>
</body>
</html>

In [24]:
pr = np.percentile(arreglo, 50)
pr

5.5

<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Obten la varianza (var)</h1>
</body>
</html>

In [25]:
vr = np.var(arreglo)
vr

8.25

<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>obtener la raiz cuadrada de cada elemento del arreglo</h1>
</body>
</html>

In [28]:
raiz = np.sqrt(arreglo)
raiz

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

<html>
<head>
    <title></title>
    <style type="text/css">
        h1
        {   
            color: BLUE
        }
    </style>
</head>
<body>
    <h1>Obten la raiz de los array, solo de los cuadrados perfectos </h1>
</body>
</html>

In [32]:
nuevoarreglo = [4, 9, 16, 25]
np.sqrt(nuevoarreglo)

array([2., 3., 4., 5.])